/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
import java.io.*;
import javax.swing.*;
public class manager extends javax.swing.JFrame {

    /**
     * Creates new form manager
     */
    public manager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_username = new javax.swing.JTextField();
        b_login = new javax.swing.JButton();
        m_password = new javax.swing.JPasswordField();
        b_exit = new javax.swing.JButton();
        m_show = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Manager LogIn Menu");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Username:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Password:");

        m_username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        m_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_usernameActionPerformed(evt);
            }
        });

        b_login.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        b_login.setText("LogIn");
        b_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_loginActionPerformed(evt);
            }
        });

        m_password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        m_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_passwordActionPerformed(evt);
            }
        });

        b_exit.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        b_exit.setText("Exit");
        b_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_exitActionPerformed(evt);
            }
        });

        m_show.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        m_show.setText("Show Password");
        m_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_showActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jButton2.setText("Click Me!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        jLabel4.setText("If you don't have an account?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_show)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(b_login, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(m_password)
                            .addComponent(m_username)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(m_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(11, 11, 11)
                .addComponent(m_show)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_login)
                    .addComponent(b_exit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_loginActionPerformed
        String username = m_username.getText();
        String password = new String(m_password.getPassword());
        boolean isLoginSuccessful = false;

        // Validate inputs
        if (username.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out username");
            return;
        }
        if (password.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out password");
            return;
        }

        // Check credentials in file
        try (BufferedReader br = new BufferedReader(new FileReader("C:\\OOP\\manager.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                // Assume file format: "username:password"
                String[] credentials = line.split(":");
                if (credentials.length == 2) {
                    String fileUsername = credentials[0].trim();
                    String filePassword = credentials[1].trim();
                    if (fileUsername.equals(username) && filePassword.equals(password)) {
                        isLoginSuccessful = true;
                        break;
                    }
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error reading file: " + e.getMessage());
            return;
        }

        // Show appropriate message and action
        if (isLoginSuccessful) {
            // Store the username in LoginManager
            LoginManager.setCurrentUser(username);
            log_UserActivity.logUserActivity(username, "Login");
            JOptionPane.showMessageDialog(null, "Successful Login!");
            managerMenu mM = new managerMenu(); // Proceed to managerMenu
            mM.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Couldn't find your account.", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_b_loginActionPerformed

    private void b_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_exitActionPerformed
        // Show a thank-you message when exit
        JOptionPane.showMessageDialog(null, "Thanks for using the system!", "Exit", JOptionPane.INFORMATION_MESSAGE);
        tryJFrame e = new tryJFrame();
        e.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b_exitActionPerformed

    private void m_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_showActionPerformed
        if (m_show.isSelected()){
            m_password.setEchoChar((char)0);
        }else{
            m_password.setEchoChar('*');
        }
    }//GEN-LAST:event_m_showActionPerformed

    private void m_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_usernameActionPerformed
        String username = m_username.getText(); // Get INPUT
        boolean usernameExists = false;

        try {
            FileReader fr = new FileReader("C:\\OOP\\manager.txt");
            BufferedReader br = new BufferedReader(fr);
            String line;

            // Check each line in the file
            while ((line = br.readLine()) != null) {
                if (line.equalsIgnoreCase(username)) { 
                    usernameExists = true;
                    break;
                }
            }

            br.close();
            fr.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error occurs while reading the file: " + e.getMessage());
        }

        // Notify the user of the result
        if (usernameExists) {
            JOptionPane.showMessageDialog(this, "Username exists!");
        } else {
            JOptionPane.showMessageDialog(this, "Username does not exist!");
        }

        // Optional: Clear the text field
        m_username.setText("");
    
    }//GEN-LAST:event_m_usernameActionPerformed

    private void m_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_passwordActionPerformed

    }//GEN-LAST:event_m_passwordActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Registration r = new Registration();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_exit;
    private javax.swing.JButton b_login;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField m_password;
    private javax.swing.JCheckBox m_show;
    private javax.swing.JTextField m_username;
    // End of variables declaration//GEN-END:variables
}
