
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class s_GenerateReceipt extends javax.swing.JFrame {

    private String username;
    
    public s_GenerateReceipt() {
        initComponents();
        username = LoginManager.getCurrentUser();
        loadPaymentRecords();
    }
    
    // Get room fee based on room type
    private int getRoomFee(String roomType) {
        int roomFee = 0;

        // Check the room type and assign corresponding fee
        if (roomType.equalsIgnoreCase("Single(Non-AC)")) {
            roomFee = 600; // Example fee for Single room
        } else if (roomType.equalsIgnoreCase("Single(AC)")) {
            roomFee = 800; // Example fee for Double room
        } else if (roomType.equalsIgnoreCase("Twin(Non-AC)")) {
            roomFee = 500; // Example fee for Suite room
        } else{
            roomFee = 600;
        }

        return roomFee;
    }
    
    private void loadPaymentRecords() {
        // Read the payment records and display all records in the table
        List<String[]> paymentData = readPaymentRecords();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Clear existing rows
        model.setRowCount(0);

        // Set column headers
        model.setColumnIdentifiers(new String[]{"PaymentID", "Username", "Room Type", "Payment Duration", "Facilities Fee", "Total Amount", "Payment Status"});

        // Add all records to the table
        for (String[] record : paymentData) {
            model.addRow(record);
        }
        
        // Make the table non-editable
        for (int i = 0; i < model.getRowCount(); i++) {
            for (int j = 0; j < model.getColumnCount(); j++) {
                jTable1.setDefaultEditor(model.getColumnClass(j), null);  // Disables editing for all cells
            }
        }
    }
    
    private List<String[]> readPaymentRecords() {
        List<String[]> paymentData = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader("C:\\OOP\\payments.txt"))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] record = line.split(":");
                paymentData.add(record);
            }
        } catch (Exception e) {
        }
        return paymentData;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Generate Receipt");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("PaymentID:");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Generate Receipt");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Back to Homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Receipt Generated Here:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel1)
                        .addContainerGap(815, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 801, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(117, 117, 117)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String paymentID = jTextField1.getText().trim();

        if (paymentID.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a PaymentID.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Read the payment records and find the record with the matching PaymentID
        List<String[]> paymentData = readPaymentRecords();
        String[] record = null;

        for (String[] data : paymentData) {
            if (data[0].equals(paymentID)) {
                record = data;
                break;
            }
        }

        if (record != null) {
            // Get the current date and time
            Date currentDate = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            String dateTime = dateFormat.format(currentDate);

            // Get the room type and facilities
            String roomType = record[2];
            int roomFee = getRoomFee(roomType); // Get room fee using the new method

            String facilitiesFee = record[4].equalsIgnoreCase("yes") ? "RM 100" : "RM 0";  // Assuming a fixed facilities fee of RM100

            // Validate and parse the number of months
            int months = 0;
            String paymentDuration = record[3].toLowerCase();

            if (paymentDuration.equals("year")) {
                months = 12;
            } else if (paymentDuration.equals("semester")) {
                months = 4;
            } else if (paymentDuration.equals("month")) {
                months = 1;
            } else {
                try {
                    months = Integer.parseInt(paymentDuration); // If it's a number, parse it directly
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Invalid payment duration.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }

            // Calculate the total amount
            int totalAmount = (roomFee * months) + 100; // Adding facilities fee (RM100)

            // Print the receipt
            log_UserActivity.logUserActivity(username, "Generate Receipt");
            String receipt = "\n"
                    + "-----------------------------------Receipt------------------------------------\n"
                    + "\n"
                    + "Payment ID: " + paymentID + "               " + "Date & Time: " + dateTime + "\n"
                    + "Username: " + record[1]           
                    + "\n"
                    + "Room Type: " + roomType + "                                             " + "RM "+roomFee + "\n" 
                    + "Payment Duration:                                                            " +"*"+ months + "\n"
                    + "Facilities Fee:                                                           " +facilitiesFee + "\n"
                    + "\n"
                    + "\n"
                    + "*********************************************************************\n"
                    + "                              Total Amount: RM" + totalAmount + "\n"
                    + "*********************************************************************\n"
                    + "\n"
                    + "                         -Thanks for using our system-";
                    

            //Display the receipt in the JTextArea1
            jTextArea1.setText(receipt);
            
            // Mark the payment as completed and update the file
            record[6] = "Paid";
            updatePaymentRecords(paymentData);
        } else {
            JOptionPane.showMessageDialog(this, "Payment record not found.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        staffMenu_ s = new staffMenu_();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void updatePaymentRecords(List<String[]> paymentData) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("C:\\OOP\\payments.txt"))) {
            for (String[] record : paymentData) {
                bw.write(String.join(":", record));
                bw.newLine();
            }
        } catch (Exception e) {
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s_GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s_GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s_GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s_GenerateReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s_GenerateReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}

