
import java.io.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author acer
 */
public class s_MakePayment extends javax.swing.JFrame {

    /**
     * Creates new form s_MakePayment
     */
    
    // File paths for booking and payment records
    private static final String BOOKING_FILE = "C:\\OOP\\bookingrecord.txt";
    private static final String PAYMENTS_FILE = "C:\\OOP\\payments.txt";

    
    public s_MakePayment() {
        initComponents();
        loadBookingRecords();
    }
    
    private void loadBookingRecords() {
        // Display booking records in a table
        List<String[]> bookingData = readBookingRecords();
        DefaultTableModel model = new DefaultTableModel() {
            // Override isCellEditable method to make the cells non-editable
            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false; // Prevent editing for all cells
            }
        };
        
        // Clear any existing rows
        model.setRowCount(0);

        // Add header with PaymentID, username, roomtype, paymentduration, facilities, and paymentstatus
        model.setColumnIdentifiers(new String[] {"PaymentID", "Username", "Room Type", "Payment Duration", "Facilities Fee", "Payment Status"});

        // Add booking records to the table
        for (String[] record : bookingData) {
            model.addRow(record);
        }
        
        // Set the model for the table
        jTable1.setModel(model);
    }

    private List<String[]> readBookingRecords() {
        List<String[]> bookingData = new ArrayList<>();
        try (BufferedReader br = new BufferedReader(new FileReader(BOOKING_FILE))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] record = line.split(":");
                // Add record to the list
                bookingData.add(record);
            }
        } catch (Exception e) {
        }
        return bookingData;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Make Payment");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Residents Username:");

        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton1.setText("Make Payment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Booking Records Table");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton2.setText("Back to Homepage");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Get the PaymentID entered by staff
    String paymentID = jTextField1.getText().trim();

    if (paymentID.isEmpty()) {
        JOptionPane.showMessageDialog(this, "PaymentID cannot be empty. Please enter a valid PaymentID.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    List<String[]> bookingData = readBookingRecords();
    boolean found = false;

    // Variables to hold booking details
    String username = "";
    String roomType = "";
    String paymentDuration = "";
    String facilities = "";
    double totalAmount = 0;

    List<String[]> updatedBookingData = new ArrayList<>();

    for (String[] record : bookingData) {
        if (record[0].equals(paymentID)) { // Match PaymentID
            found = true;

            if (record[5].equalsIgnoreCase("Paid")) {
                JOptionPane.showMessageDialog(this, "This payment has already been made.", "Information", JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            // Extract data
            username = record[1];
            roomType = record[2];
            paymentDuration = record[3];
            facilities = record[4];

            // Validate roomType
            double roomRate = getRoomRate(roomType);
            if (roomRate == 0) {
                JOptionPane.showMessageDialog(this, "Invalid room type in booking records. Please check the data.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Calculate total payment
            boolean isFacilitiesFeeIncluded = facilities.equalsIgnoreCase("yes");
            totalAmount = calculateTotalPayment(roomRate, paymentDuration, isFacilitiesFeeIncluded);

            // Update payment status
            record[5] = "Paid";  // Update payment status to Paid
            updatedBookingData.add(record);

            // Save payment details
            savePaymentData(paymentID, username, roomType, paymentDuration, facilities, totalAmount, "Paid");
            log_UserActivity.logUserActivity(username, "Make Payment");
            JOptionPane.showMessageDialog(this, "Payment successful for PaymentID: " + paymentID + ". Total: RM" + totalAmount, "Success", JOptionPane.INFORMATION_MESSAGE);
        } else {
            updatedBookingData.add(record); // Keep unchanged records
        }
    }

    if (found) {
        saveUpdatedBookingRecords(updatedBookingData); // Save updated booking records
        loadBookingRecords(); // Refresh table
    } else {
        JOptionPane.showMessageDialog(this, "PaymentID not found in the booking records. Please check and try again.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Go to staff menu
        staffMenu_ s = new staffMenu_();
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private double getRoomRate(String roomType) {
        // Define rates based on room type
        switch (roomType) {
            case "Single":
                return 600;  // RM200 for a single room
            case "Twin":
                return 500;  // RM300 for a double room
            case "Single(AC)":
                return 800;  // RM200 for a single room
            case "Twin(AC)":
                return 600;
            default:
                return 0;  // Default rate for unknown room types
        }
    }

    private double calculateTotalPayment(double roomRate, String paymentDuration, boolean isFacilitiesFeeIncluded) {
        double durationMultiplier = paymentDuration.equalsIgnoreCase("Year") ? 12 : 1;
        double facilitiesFee = isFacilitiesFeeIncluded ? 100 : 0;
        return (roomRate * durationMultiplier) + facilitiesFee;
    }

    private void saveUpdatedBookingRecords(List<String[]> updatedBookingData) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(BOOKING_FILE))) {
            for (String[] record : updatedBookingData) {
                bw.write(String.join(":", record));
                bw.newLine();
            }
        } catch (Exception e) {
        }
    }

    private void savePaymentData(String paymentID, String username, String roomType, String paymentDuration, String facilities, double totalAmount, String paymentStatus) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(PAYMENTS_FILE, true))) {
            String record = String.format("%s:%s:%s:%s:%s:%.2f:%s", paymentID, username, roomType, paymentDuration, facilities, totalAmount, paymentStatus);
            bw.write(record);
            bw.newLine();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saving payment data. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(s_MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(s_MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(s_MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(s_MakePayment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new s_MakePayment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
